package: yrewrite_scheme
version: '3.1.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yrewrite_scheme/
pages:
    yrewrite/yrewrite_scheme:
        title: 'translate:yrewrite_scheme_title'
        perm: admin
        icon: rex-icon fa-exchange

requires:
    packages:
        yrewrite: '>=2.1.0'
conflicts:
    packages:
        xcore: '>=0.0.0'
