package: yrewrite_scheme
version: '2.1.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yrewrite_scheme/
pages:
    yrewrite/yrewrite_scheme:
        title: 'YRewrite Scheme'
        perm: admin
        icon: rex-icon fa-exchange

requires:
    packages:
        yrewrite: '>=2.1.0'
