package: yrewrite_scheme
version: '3.6.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yrewrite_scheme/
pages:
    yrewrite/yrewrite_scheme:
        title: 'translate:yrewrite_scheme_title'
        perm: admin
        icon: rex-icon fa-exchange

requires:
    redaxo: '^5.11.2'
    packages:
        yrewrite: '>=2.7'
